# Site settings
title: WTM Zaragoza 2023
hashtag: wtmz23
email: womentechmakerszgz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  El 11 de noviembre de 2023 se celebra la quinta edición del evento Women Techmakers en Zaragoza.
  Women Techmakers es de una iniciativa promovida a nivel global por Google para visibilizar a las mujeres en el ámbito de la tecnología.
  Este evento quiere crear una comunidad con visibilidad, generando recursos que impulsen la innovación y la participación de las mujeres en este campo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Mulleres Tech

# User setting
owner:
#email: womentechmakerszgz@gmail.com
email: wtmz@mullerestech.es
facebook_username:
twitter_username: WTMZaragoza
instagram_username: WTMZaragoza
github_username: MulleresTechZgz
address:
  - line: ETOPIA Centro de Arte y Tecnología
  - line: Av. de la Ciudad de Soria, 8 (50003) Zaragoza
  # Feel free to add more lines here 
telephone:
copyright:

# Tickets
sold_out_tickets_first: true
sold_out_tickets: false

# Timezone
timezone: Europe/Madrid

# API settings
google_api_key:

# Build settings
markdown: kramdown
theme: 

#Dates
end_c4p: 10/09/2017 23:59:59

#Introduction
intro_event:

#List for event info
#event_infos:
#  - title: ¿Qué es Women Techmakers?
#    content: Se trata de una iniciativa promovida a nivel global por Google para <strong>visibilizar a las mujeres</strong> en el ámbito de la tecnología.<br/><br/>Women Techmakers quiere crear una comunidad con visibilidad, generando recursos que impulsen la innovación y la participación de las mujeres en este campo.<br/>
#    image: img/wtmz18/wtmz18_organizacion_y_ponentes.jpg
#  - title: ¿A quién está dirigido el evento?
#    content: Se trata de un <strong>evento abierto</strong> a cualquier persona interesada en el mundo de la tecnología.<br/><br/>Queremos abarcar diferentes temas como <strong>nuevas tecnologías, agile, comunicación, desarrollo web, UX</strong> o cualquier tema interesante del sector.<br/><br/>La asistencia al evento está abierta tanto a hombres como a mujeres, pero las ponentes serán únicamente mujeres, ya que uno de los objetivos es darles visibilidad así como ofrecer ayuda y colaboración.
#    image: img/wtmz18/wtmz18_foto_grupo.jpg
#  - title: ¿Dónde se ha celebrado hasta ahora?
#    content: En Barcelona con <span class="wtm-highlight">18</span> ponentes<br/>En Gijón <span class="wtm-highlight">12</span> ponentes<br/>En Jaén <span class="wtm-highlight">3</span> ponentes<br/>En Logroño <span class="wtm-highlight">5</span> ponentes<br/>En Madrid <span class="wtm-highlight">38</span> ponentes<br/>En Tenerife <span class="wtm-highlight">9</span> ponentes<br/>En Valencia <span class="wtm-highlight">16</span> ponentes<br/>En Vigo <span class="wtm-highlight">6</span> ponentes
#    image: img/imgs_dossier/MapaSpainWTM.jpg
#  - title: Cifras de WTM Zaragoza 2018
#    content: Más de 285 asistentes<br/><br/>Repartidos en 2 tracks de charlas más 2 aulas de talleres<br/><br/>94 propuestas recibidas en el Call for Papers<br/><br/>35 ponentes mujeres y 4 mentoras<br/><br/>22 charlas impartidas y 3 talleres<br/><br/>30 patrocinadores y colaboradores<br/><br/>10 medios de comunicacion se hicieron eco de nuestro evento<br/><br/>Conseguimos alcanzar los 1000 followers en Twitter
#    image: img/wtmz18/wtmz18_organizadoras_power.jpg

#List for organizers
organizers:
  - name: Esther Borao
    text: 
    image: img/organizadoras/EstherBorao_a
    image_card: img/organizadoras/fichas/EstherBorao
    twitter_account: EstherBorao
    linkedin_account: 
    instagram_account: estherborao
    mail_account: esther@mullerestech.es
  - name: Miriam Durán
    text: 
    image: img/organizadoras/MiriamDuran_a
    image_card: img/organizadoras/fichas/MiriamDuran
    twitter_account: miripi
    linkedin_account: 
    instagram_account: 
    mail_account: miriam@mullerestech.es
  - name: Cynthia Gálvez
    text: 
    image: img/organizadoras/CynthiaGalvez_a
    image_card: img/organizadoras/fichas/CynthiaGalvez
    twitter_account: icynthia
    linkedin_account: 
    instagram_account: 
    mail_account: cynthia@mullerestech.es
  - name: Patricia Heredia
    text: 
    image: img/organizadoras/PatriciaHeredia_a
    image_card: img/organizadoras/fichas/PatriciaHeredia
    twitter_account: pherediagil
    linkedin_account: 
    instagram_account: pherediagil
    mail_account: patricia@mullerestech.es
  - name: Laura Lacarra
    text: 
    image: img/organizadoras/LauraLacarra_a
    image_card: img/organizadoras/fichas/LauraLacarra
    twitter_account: LauraLacarra
    linkedin_account: 
    instagram_account: lauralacarra
    mail_account: laura@mullerestech.es
  - name: Cristina Pérez
    text: 
    image: img/organizadoras/CristinaPerez_a
    image_card: img/organizadoras/fichas/CristinaPerez
    twitter_account: cristinapg
    linkedin_account: 
    instagram_account: 
    mail_account: cristina@mullerestech.es
  - name: Jessica Redrado
    text: 
    image: img/organizadoras/JessicaRedrado_a
    image_card: img/organizadoras/fichas/JessicaRedrado
    twitter_account: Jessi_Redrado
    linkedin_account: jessica-redrado-martinez
    instagram_account: jessi_redrado
    mail_account: jessica@mullerestech.es
  - name: Ana Sánchez
    text: 
    image: img/organizadoras/AnaSanchez_a
    image_card: img/organizadoras/fichas/AnaSanchez
    twitter_account: anasanalva
    linkedin_account: anasanchezalvarez
    instagram_account: 

#List for guests
#guests:
#  - name: Fulanita Detal
#    bio: ''
#    image: img/ponentes/foto4
#    image_card: 
#    twitter_account: 
#    linkedin_account: 

#List for speakers
speakers:
  - name: Elisa Amorós Galindo
    short_name: Elisa Amorós
    bio: 'Diseñadora e ingeniera a partes iguales, combina la parte tecnológica y la creativa para dar soluciones a proyectos digitales. Su labor dentro de la empresa aragonesa Imascono se centra en diseñar experiencias a medida para áreas como el marketing o la formación online, apoyándose en tecnologías como la web, la Realidad Aumentada o la Realidad Virtual.<br/><br/>Ingeniera en Diseño Industrial y Desarrollo de producto y especializada en Experiencia de Usuario, lleva más de 9 años dedicada al diseño de productos digitales.'
    image: img/ponentes/ElisaAmoros
    image_card: img/ponentes/fichas/ElisaAmoros
    twitter_account: 
    linkedin_account: elisaamoros
    instagram_account: amoroskova
  - name: Beatriz Franco García
    short_name: Beatriz Franco García
    bio: 'Ingeniera informática en la Universidad de Zaragoza y máster de Inteligencia Artificial en la UNIR (La Rioja). Comencé mi andadura en ITAINNOVA como investigadora en el área de Inteligencia Artificial, Sistemas Cognitivos y Bigdata adquiriendo experiencia en algoritmos de Machine Learning y Deep Learning tanto para el análisis de datos numéricos como en la comprensión y tratamiento de textos mediante algoritmos y técnicas de procesamiento de lenguaje natural en español. Un parón de un año en Bitbrain me ha aportado conocimiento sobre el procesamiento y sincronización de bioseñales.'
    image: img/ponentes/BeatrizFranco
    image_card: img/ponentes/fichas/BeatrizFranco
    twitter_account: 95_beafranco
    linkedin_account: beatriz-franco-151000130
    instagram_account: bfranco95
  - name: Aránzazu García Aso
    short_name: Aránzazu García
    bio: 'Aránzazu García Aso es licenciada en Ciencias Matemáticas por la Universidad de Zaragoza y pertenece al cuerpo de Titulados Superiores de Informática del Gobierno de Aragón. <br/><br/>Toda su carrera profesional ha estado vinculada al desarrollo de proyectos de software. Desde 2019 trabaja como asesora técnica de Servicios Digitales de Aragón donde se encarga de la dirección y coordinación de proyectos. Anteriormente formó parte del servicio de informática de la DG de Tributos (2005-2019). Previamente, trabajó en el sector financiero dentro del desarrollo de SW de Caja Madrid (2000-2004).'
    image: img/ponentes/AranzazuGarcia
    image_card: img/ponentes/fichas/AranzazuGarcia
    twitter_account: aranchagarc
    linkedin_account: ar%C3%A1nzazu-garc%C3%ADa-aso-44372a238
    instagram_account: 
  - name: Rosa Monge Prieto
    short_name: Rosa Monge
    bio: 'Fulanita Detal'
    image: img/ponentes/RosaMonge
    image_card: img/ponentes/fichas/RosaMonge
    twitter_account: RoisinMinea
    linkedin_account: rosamongeprieto
    instagram_account: RoisinMinea
  - name: Esther Nuez Bernal
    short_name: Esther Nuez
    bio: 'Esther Nuez es Ingeniera Informática por la Universidad de Zaragoza y pertenece al cuerpo de Titulados Superiores de Informática del Gobierno de Aragón desde 2015. Desde entonces trabaja en Servicios Digitales de Aragón, donde actualmente se encarga de la dirección técnica y coordinación de varios proyectos. Anteriormente trabajó en el sector privado donde participó en proyectos de banca electrónica y en proyectos para la Administración de Justicia.'
    image: img/ponentes/EstherNuez
    image_card: img/ponentes/fichas/EstherNuez
    twitter_account: EstherNuez
    linkedin_account:
    instagram_account: 
  - name: Némesis Pérez Zerga
    short_name: Némesis Pérez
    bio: 'Némesis Zerga, Diseño Gráfico y Comunicación Visual, Asunción-Paraguay 2016. Es creativa publicitaria, trabajó en campañas de sensibilización para onegés internacionales como Ammistía Internacional, WWF y Aldeas Infantiles. Reside en Zaragoza desde el 2019, emprende CuenTale, una biblioteca digital infantil que propone temas basados en derechos humanos para dialogar con la infancia. Con esta cuentoteca ha participado de numerosos programas de emprendimiento, innovación educativa y empoderamiento femenino en Aragón'
    image: img/ponentes/NemesisPerez
    image_card: img/ponentes/fichas/NemesisPerez
    twitter_account: nemezerga
    linkedin_account: n%C3%A9mesis-zerga-23009a77
    instagram_account: nemezerga
    instagram_account_2: cuentotecadigital
  - name: Ana Rodríguez Salinas
    short_name: Ana Rodríguez
    bio: 'Joven comunicadora y amante de las nuevas tecnologías. Enfocada en el Branding y la Comunicación de Imascono, su labor dentro del estudio creativo es acercar los últimos proyectos e innovaciones tanto a la comunidad tecnológica como al público general. Algo que requiere estar al tanto de las tendencias tecnológicas y también de todos los canales de comunicación disponibles.<br/><br/>Graduada en Comunicación Audiovisual (UC3M), compagina su puesto en Imascono con la investigación dentro del área de marketing, con la publicación de artículos académicos en las revistas científicas españolas (RedMarka).'
    image: img/ponentes/AnaRodriguez
    image_card: img/ponentes/fichas/AnaRodriguez
    twitter_account: anarsalinas
    linkedin_account: ana-i-rodriguez-salinas
    instagram_account: ana.rsalinas

#List for mentors
#mentors:
#  - name: Fulanita Detal
#    short_name: Fulanita Detal
#    bio: 'Fulanita Detal'
#    image: img/ponentes/foto2_1
#    image_card: 
#    twitter_account: 
#    linkedin_account:
#  - name: Fulanita Detal
#    short_name: Fulanita Detal
#    bio: 'Fulanita Detal'
#    image: img/ponentes/foto2_5
#    image_card: 
#    twitter_account: 
#    linkedin_account:
#  - name: Fulanita Detal
#    short_name: Fulanita Detal
#    bio: 'Fulanita Detal'
#    image: img/ponentes/foto2_3
#    image_card: 
#    twitter_account: 
#    linkedin_account:
#  - name: Fulanita Detal
#    short_name: Fulanita Detal
#    bio: 'Fulanita Detal'
#    image: img/ponentes/foto2_2
#    image_card: 
#    twitter_account: 
#    linkedin_account:

#List for volunteers
volunteers:
  - name: Fulanita Detal
    short_name: Fulanita Detal
    bio: 'Fulanita Detal'
    image: img/ponentes/foto1
    image_card: 
    twitter_account: 
    linkedin_account:
  - name: Fulanita Detal
    short_name: Fulanita Detal
    bio: 'Fulanita Detal'
    image: img/ponentes/foto4
    image_card: 
    twitter_account: 
    linkedin_account:
  - name: Fulanita Detal
    short_name: Fulanita Detal
    bio: 'Fulanita Detal'
    image: img/ponentes/foto2
    image_card: 
    twitter_account: 
    linkedin_account:
  - name: Fulanita Detal
    short_name: Fulanita Detal
    bio: 'Fulanita Detal'
    image: img/ponentes/foto3
    image_card: 
    twitter_account: 
    linkedin_account:

#List for sponsors
#sponsors_platinum:
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa1.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa2.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa3.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa4.png
#    web: #
#    twitter:

#sponsors_gold:
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa1.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa2.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa3.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa4.png
#    web: #
#    twitter: 

#sponsors_silver:
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa1.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa2.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa3.png
#    web: #
#    twitter:     

#sponsors_others:
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa1.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa2.png
#    web: #
#    twitter: 
#  - name: Empresa Genérica
#    text: 
#    image: img/patrocinadores/generico/empresa3.png
#    web: #
#    twitter: 

# Agenda
talks_track_1:
  - time: '09:30-10:00'
    track: all
    name: REGISTRO
    descrip: 
    speaker: 
    bio_speaker: 
    twitter_speaker: 
  - time: '10:00-10:15'
    track: all
    name: 'PRESENTACIÓN Staff WTM Zaragoza'
    #second_name: 'Inauguración: Pilar Alegría, Consejera de Innovación, Investigación y Universidad y <br/> Elena Giner, Consejera de Participación, Transparencia y Gobierno Abierto'
    #second_name: 'Inauguración: Elena Giner (Ayuntamiento de Zaragoza) y Pilar Alegría (Gobierno de Aragón)'
    descrip: 
    speaker: 
    bio_speaker: 
    twitter_speaker: 
  - time: '10:15-10:55'
    track: 1
    name: 'El Metaverso de la Realidad Extendida'
    descrip: 'Desde el cambio de estrategia de Facebook a Meta a finales del 2021, el sector tecnológico se ha movilizado a lo grande. Dirigiendo todos sus esfuerzos en el desarrollo de lo que ya se considera la siguiente generación de internet.<br/><br/>El Metaverso se abre ante nuestros ojos como el universo virtual definitivo, al que se espera que el comercio, el entretenimiento, el ocio, cultura, industria y negocios se trasladen a lo largo de los próximos años. Pero el cómo, todavía está bajo construcción. Una de las posibles soluciones la protagoniza el estudio tecnológico Imascono, quienes desde su línea Business To Metaverse, crean puentes entre las tecnologías de la Realidad Extendida con las nuevas experiencias dentro del universo virtual. <br/><br/>Para hablar de todas estas tecnologías inmersivas y sobre los proyectos actuales dentro del Metaverso nos acompañan Elisa Amorós y Ana Rodríguez en una ponencia donde la teoría y la práctica, la ciencia ficción y la realidad se unen por un mismo objetivo: acercar las nuevas tendencias y tecnologías a todos los públicos.'
    speaker: 'Elisa Amorós Galindo y Ana Rodríguez Salinas'
    bio_speaker: 
    twitter_speaker: 
    url_youtube: 
  - time: '11:00-11:40'
    track: 1
    name: 'Inteligencia Artificial con propósito · Caso de innovación educativa: iCuento'
    descrip: '¿Inteligencia artificial en el sector educativo? Presentaremos el caso "iCuento" desarrollado en conjunto con ITAINNOVA como parte de los proyectos seleccionados en las fase II de la convocatoria INNOIDEA.<br/><br/>Luego de presentar el proyecto donde realizamos un motor de IA que sugiere frases para iniciar, continuar o concluir una frase de un cuento, describiremos las estructuras empleadas, desarrollaremos el proceso de trabajo realizado, y evaluaremos los resultados además de intentar responder desde nuestra experiencia con el caso el debate que plantea la IA en el sector educativo y como gracias a nuestras lecturas, canalizamos el uso de la herramienta en aulas de 5to. y 6to. de primaria.'
    speaker: 'Beatriz Franco García y Némesis Pérez Zerga '
    bio_speaker: 
    twitter_speaker: 
    url_youtube:
  - time: '11:45-12:15'
    track: all
    name: DESCANSO CAFÉ
    descrip: 
    speaker: 
    bio_speaker: 
    twitter_speaker: 
  - time: '12:15-12:55'
    track: 1
    name: 'Cómo hacer ingeniería del SW en una administración pública y no morir en el intento (de momento)'
    descrip: '¿Se puede hacer Ingeniería del SW en la Administración Pública? ¿Son dos mundos incompatibles? Contaremos nuestra experiencia realista desde una unidad de la Administración en la que se trabaja para mejorar los servicios públicos con ayuda del diseño y la tecnología. No pretende dar una perspectiva teórica, sino contar situaciones y proyectos reales que se abordan actualmente en Servicios Digitales de Aragón.'
    speaker: 'Aránzazu García Aso y Esther Nuez Bernal'
    bio_speaker: 
    twitter_speaker: 
    url_youtube: 
  - time: '13:00-13:40'
    track: 1
    name: '¿Qué hace una ingeniera como tú en una empresa (biotecnológica) como esa?'
    descrip: 'Experiencia emprendedora de transferencia de conocimiento desde el mundo de la academia a la fundación de una startup.'
    speaker: 'Rosa Monge Prieto'
    bio_speaker: 
    twitter_speaker: 
    url_youtube: 
  - time: '13:45-14:00'
    track: all
    name: 'CIERRE Staff WTM Zaragoza'
    #second_name: 'Clausura: Elena Giner, Consejera de Participación, Transparencia y Gobierno Abierto'
    descrip: 
    speaker: 
    bio_speaker: 
    twitter_speaker: 
  - time: '14:00-14:10'
    track: all
    name: Fotografía de grupo
    descrip: 
    speaker: 
    bio_speaker: 
    twitter_speaker: 
  - time: '14:10-15:45'
    track: all
    name: COMIDA Y NETWORKING
    descrip: 
    speaker: 
    bio_speaker: 
    twitter_speaker: 

talks_track_2: 

workshops_track_1: 

workshops_track_2: 
